steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Fetching SSH key from Secret Manager..."
        gcloud secrets versions access latest --secret=gopi-test > gopi.pem
        chmod 600 gopi.pem

        echo "Copying updated file to VM..."
        scp -o StrictHostKeyChecking=no -i gopi.pem /workspace/index.html gopi@34.47.192.3:/tmp/index.html

        echo "Connecting to VM..."
        ssh -o StrictHostKeyChecking=no -i gopi.pem gopi@34.47.192.3 "
          echo 'Backing up existing file...'
          sudo cp /var/www/html/index.html /var/www/html/index-$(date +%s).bak

          echo 'Deploying new index.html...'
          sudo mv /tmp/index.html /var/www/html/index.html
          sudo chmod 644 /var/www/html/index.html
          
          echo 'Restarting Apache...'
          sudo systemctl restart apache2

          echo 'Deployment completed successfully!'
        "

options:
  logging: CLOUD_LOGGING_ONLY
