steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Cloning repo..."
        git clone https://github.com/gopinath940/gopi-test-cicd.git repo

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Fetching private key..."
        gcloud secrets versions access latest --secret="gopi-ssh-key" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa

        echo "Copying file to VM..."
        scp -o StrictHostKeyChecking=no \
          repo/index.html \
          gopi@34.47.192.3:/var/www/html/index.html

        echo "Deployment complete!"

timeout: "1200s"
