steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Connecting to VM via SSH..."
        chmod 600 /root/.ssh/gopi.pem

        ssh -o StrictHostKeyChecking=no -i /root/.ssh/gopi.pem gopi@34.47.192.3 "
          echo 'Taking backup of existing file...'
          sudo cp /var/www/html/index.html /var/www/html/index-$(date +%s).bak

          echo 'Deploying new file...'
          sudo cp /workspace/index.html /var/www/html/index.html

          echo 'Deployment completed successfully!'
        "

# Disable bucket logs requirement
options:
  logging: CLOUD_LOGGING_ONLY
